import { expect, test } from "@playwright/test";

test("developer can browse catalog, create an environment, and review admin readiness", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByRole("heading", { name: "Developer portal" })).toBeVisible();
  await expect(page.getByText("Environment operations")).toBeVisible();
  await expect(page.getByText("Access context")).toBeVisible();
  await expect(page.getByText("Approval queue")).toBeVisible();
  await expect(page.getByText("Control plane queue")).toBeVisible();

  await page.getByRole("button", { name: "Details" }).first().click();
  await expect(page.getByRole("heading", { name: "Environment details" })).toBeVisible();
  await expect(page.getByText("Provisioning jobs")).toBeVisible();
  await expect(page.getByText("Audit trail")).toBeVisible();

  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Golden path catalog" })).toBeVisible();

  await page.getByRole("button", { name: "View details" }).first().click();
  await expect(page.getByRole("heading", { name: "Template details" })).toBeVisible();
  await expect(page.getByText("Integration readiness")).toBeVisible();

  await page.getByRole("button", { name: "Use this golden path" }).click();
  await expect(page.getByRole("heading", { name: "Create environment" })).toBeVisible();
  await page.getByLabel("Environment name").fill("smoke-api-dev");
  await page.getByRole("button", { name: "Launch simulated provisioning" }).click();

  await expect(page.getByRole("heading", { name: "Environment status" })).toBeVisible();
  await expect(page.getByText("Provisioning job queued")).toBeVisible();
  await expect(page.getByText("Template validated")).toBeVisible();

  await page.getByRole("button", { name: "Admin", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Platform admin" })).toBeVisible();
  await expect(page.getByText("Access model")).toBeVisible();
  await expect(page.getByText("Identity boundary")).toBeVisible();
  await expect(page.getByText("Manage providers, registry, preflight, lifecycle, and audit export")).toBeVisible();
  await expect(page.getByRole("tab", { name: "Providers Config and adapters" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Control plane Jobs and approvals" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Operations Lifecycle and audit" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Governance Queues and controls" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Templates Catalog and ownership" })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Production readiness review" })).toBeVisible();
  await page.getByRole("button", { name: "Run readiness review" }).click();
  await expect(page.getByText("Release readiness gate")).toBeVisible();
  await expect(page.getByText("OIDC boundary")).toBeVisible();
  await page.getByRole("tab", { name: "Providers Config and adapters" }).click();
  await expect(page.getByText("Integration configuration")).toBeVisible();
  await expect(page.getByText("Lab adapter pilot")).toBeVisible();
  await expect(page.getByText("Prism read-only inventory")).toBeVisible();
  await expect(page.getByText("Provider readiness")).toBeVisible();
  await expect(page.getByText("Adapter enablement contract")).toBeVisible();
  await page.getByLabel("Endpoint").first().fill("https://prism.lab.example");
  await page.getByLabel("Credential profile").first().fill("nci-readonly");
  await page.getByRole("button", { name: "Save" }).first().click();
  await expect(page.getByText("Configuration saved")).toBeVisible();
  await page.getByRole("button", { name: "Check" }).first().click();
  await expect(page.getByText("Reachable", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Credential reference diagnostics" })).toBeVisible();
  await expect(page.getByText("NCI credential reference")).toBeVisible();
  await expect(page.getByText("Only credential profile references are stored. Access material must remain outside NDC Studio.").first()).toBeVisible();
  await page.getByRole("button", { name: "Discover" }).first().click();
  await expect(page.getByText("Read-only candidate")).toBeVisible();
  await expect(page.getByText("Provisioning disabled").first()).toBeVisible();
  await page.getByRole("button", { name: "Import inventory" }).click();
  await expect(page.getByText("Rocky Linux 9 Hardened").first()).toBeVisible();
  await expect(page.getByText("Profile candidate").first()).toBeVisible();
  await page.getByRole("button", { name: "Review adapter enablement" }).click();
  await expect(page.getByText("Real adapter enablement remains gated")).toBeVisible();
  await expect(page.getByText("Approved lab scope", { exact: true })).toBeVisible();
  await expect(page.getByText("create_vm", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Control plane Jobs and approvals" }).click();
  await expect(page.getByText("Provisioning control plane")).toBeVisible();
  await expect(page.getByRole("heading", { name: "VM sandbox dry-run" })).toBeVisible();
  await page.getByRole("button", { name: "Generate dry-run" }).click();
  await expect(page.getByText("AHV image approved")).toBeVisible();
  await expect(page.getByText("Quota within sandbox limit")).toBeVisible();
  await expect(page.getByText("Rollback plan")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab authorization and lifecycle proof" })).toBeVisible();
  await page.getByRole("button", { name: "Record lab scope" }).click();
  await expect(page.locator("span").filter({ hasText: "Authorized lab scope / controlled provisioning test window" })).toBeVisible();
  await expect(page.getByText("Provider coverage", { exact: true })).toBeVisible();
  await expect(page.getByText("Target endpoints documented", { exact: true })).toBeVisible();
  await expect(page.getByText("Rollback owner assigned", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Operations Lifecycle and audit" }).click();
  await expect(page.getByRole("heading", { name: "Audit export boundary" })).toBeVisible();
  await page.getByRole("button", { name: "Prepare audit export" }).click();
  await expect(page.getByText("Audit export readiness")).toBeVisible();
  await page.getByRole("tab", { name: "Control plane Jobs and approvals" }).click();
  await expect(page.getByRole("heading", { name: "Rollback and destroy proof" })).toBeVisible();
  await page.getByRole("button", { name: "Record rollback proof" }).click();
  await expect(page.getByText("Ready for controlled create")).toBeVisible();
  await expect(page.getByText("Inventory reconciliation referenced")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Controlled provisioning gate" })).toBeVisible();
  await page.getByRole("button", { name: "Request gate review" }).click();
  await expect(page.getByText("Manual approval required")).toBeVisible();
  await expect(page.getByText("Authorized scope attached")).toBeVisible();
  await expect(page.getByText("Mutation kill switch enabled")).toBeVisible();
  await page.getByRole("button", { name: "Approve gate" }).click();
  await expect(page.getByText("Mutation disabled")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Controlled create authorization" })).toBeVisible();
  await page.getByRole("button", { name: "Review authorization" }).click();
  await expect(page.getByText("Live adapter authorization envelope")).toBeVisible();
  await expect(page.getByText("Active pentest scope", { exact: true })).toBeVisible();
  await expect(page.getByText("Active authorized pentest scope is required before live adapter authorization.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "AHV create adapter contract" })).toBeVisible();
  await page.getByRole("button", { name: "Review AHV create contract" }).click();
  await expect(page.getByText("Disabled AHV create contract")).toBeVisible();
  await expect(page.getByText("Payload fields approved", { exact: true })).toBeVisible();
  await expect(page.getByText("create_vm", { exact: true }).first()).toBeVisible();
  await page.getByRole("button", { name: "Record lifecycle proof" }).click();
  await expect(page.getByText("Controlled gate approved").first()).toBeVisible();
  await expect(page.getByRole("heading", { name: "AHV controlled preflight" })).toBeVisible();
  await page.getByRole("button", { name: "Run AHV preflight" }).click();
  await expect(page.getByText("Fail-closed AHV boundary")).toBeVisible();
  await expect(page.getByText("Preflight blocked")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Platform service flows" })).toBeVisible();
  await page.getByRole("button", { name: "Plan NDB PostgreSQL" }).click();
  await expect(page.getByText("VM lifecycle proven")).toBeVisible();
  await expect(page.getByText("Complete controlled VM create, verify, rollback, and destroy proof before platform services are enabled.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Platform service preflight" })).toBeVisible();
  await page.getByRole("button", { name: "Run service preflight" }).click();
  await expect(page.getByText("Fail-closed service boundary")).toBeVisible();
  await expect(page.getByText("NDB real adapter switch is disabled.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Platform service adapter contracts" })).toBeVisible();
  await page.getByRole("button", { name: "Review service contract" }).click();
  await expect(page.getByText("Disabled service adapter contracts")).toBeVisible();
  await expect(page.getByText("Payload fields approved", { exact: true }).last()).toBeVisible();
  await expect(page.getByText("create_database", { exact: true }).last()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Provider release readiness" })).toBeVisible();
  await expect(page.getByText("Provider release readiness summary")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Provider release gates" })).toBeVisible();
  await page.getByRole("button", { name: "Review NDB" }).click();
  await expect(page.getByText("Provider release evidence envelope")).toBeVisible();
  await expect(page.getByText("Provider contract evidence ready", { exact: true })).toBeVisible();
  await expect(page.getByText("NDC_NDB_REAL_ADAPTER_ENABLED: disabled").last()).toBeVisible();
  await expect(page.getByText("smoke-api-dev").first()).toBeVisible();
  await page.getByRole("button", { name: "Advance" }).first().click();
  await expect(page.getByText("Validating")).toBeVisible();
  await expect(page.getByText("Approval queue")).toBeVisible();
  await expect(page.getByText("ml-reco-lab").first()).toBeVisible();
  await page.getByRole("button", { name: "Approve" }).first().click();
  await expect(page.getByText("Provisioning").first()).toBeVisible();
  await page.getByRole("tab", { name: "Operations Lifecycle and audit" }).click();
  await expect(page.getByRole("heading", { name: "Private cloud lifecycle" })).toBeVisible();
  await page.getByRole("button", { name: "Extend" }).click();
  await expect(page.getByText("Operational lifecycle requests")).toBeVisible();
  await expect(page.getByText("Operator runbook")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Audit export boundary" })).toBeVisible();
  await expect(page.getByText("Audit export readiness")).toBeVisible();
  await expect(page.getByText("Sensitive credential material is excluded from audit events.")).toBeVisible();
  await expect(page.getByText("retention window", { exact: true })).toBeVisible();
  await expect(page.getByText("Manifest destination: browser-mock")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Release evidence exports" })).toBeVisible();
  await page.getByRole("button", { name: "Prepare release evidence" }).click();
  await expect(page.getByText("Release evidence manifest")).toBeVisible();
  await expect(page.getByText("Release evidence exports contain references and metadata only; no inline auth material.")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Controlled lab release runbook" })).toBeVisible();
  await page.getByRole("button", { name: "Prepare runbook" }).click();
  await expect(page.getByText("Operator release runbook")).toBeVisible();
  await expect(page.getByText("Required sign-offs")).toBeVisible();
  await expect(page.getByText("Stop conditions", { exact: true }).last()).toBeVisible();
  await expect(page.getByRole("heading", { name: "Controlled lab dry-run window" })).toBeVisible();
  await page.getByRole("button", { name: "Schedule dry-run window" }).click();
  await expect(page.getByText("Readiness checklist")).toBeVisible();
  await expect(page.getByText("Emergency stop contacts", { exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab window evidence exports" })).toBeVisible();
  await page.getByRole("button", { name: "Prepare window evidence" }).click();
  await expect(page.getByText("Lab window evidence manifest")).toBeVisible();
  await expect(page.getByText("Linked evidence")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab evidence review queue" })).toBeVisible();
  await page.getByRole("button", { name: "Review evidence package" }).click();
  await expect(page.getByText("Reviewer decisions", { exact: true })).toBeVisible();
  await expect(page.getByText("Reviewer decisions complete")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab execution proposal envelope" })).toBeVisible();
  await page.getByRole("button", { name: "Review proposal envelope" }).click();
  await expect(page.getByText("Envelope evidence", { exact: true })).toBeVisible();
  await expect(page.getByText("Lab evidence review accepted")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab execution proposal exports" })).toBeVisible();
  await page.getByRole("button", { name: "Prepare proposal export" }).click();
  await expect(page.getByText("Proposal export manifest")).toBeVisible();
  await expect(page.getByText("Proposal export evidence", { exact: true })).toBeVisible();
  await page.getByRole("tab", { name: "Governance Queues and controls" }).click();
  await page.getByRole("button", { name: "Destroy" }).first().click();
  await expect(page.getByText("Destroying").first()).toBeVisible();
  await page.getByRole("tab", { name: "Templates Catalog and ownership" }).click();
  await expect(page.getByText("Image and template catalog")).toBeVisible();
  await expect(page.getByText("Template registry")).toBeVisible();
  await expect(page.getByText("Policy bundles")).toBeVisible();
  await expect(page.getByText("Regulated Data Service").first()).toBeVisible();
  await page.getByRole("button", { name: "Submit review" }).first().click();
  await expect(page.getByText("Pending approval").first()).toBeVisible();
  await page.getByRole("button", { name: "Approve publish" }).first().click();
  await expect(page.getByText("Published").first()).toBeVisible();
  await expect(page.getByText("Template governance")).toBeVisible();
});
