import { expect, test } from "@playwright/test";

test("developer can browse catalog, create an environment, and review admin readiness", async ({ page }) => {
  await page.goto("/");

  await expect(page.getByRole("heading", { name: "Developer portal" })).toBeVisible();
  await expect(page.getByText("Environment operations")).toBeVisible();
  await expect(page.getByText("Access context")).toBeVisible();
  await expect(page.getByText("Approval queue")).toBeVisible();
  await expect(page.getByText("Control plane queue")).toBeVisible();

  await page.getByRole("button", { name: "Details" }).first().click();
  await expect(page.getByRole("heading", { name: "Environment details" })).toBeVisible();
  await expect(page.getByText("Provisioning jobs")).toBeVisible();
  await expect(page.getByText("Audit trail")).toBeVisible();

  await page.getByRole("button", { name: "Catalog", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Golden path catalog" })).toBeVisible();

  await page.getByRole("button", { name: "View details" }).first().click();
  await expect(page.getByRole("heading", { name: "Template details" })).toBeVisible();
  await expect(page.getByText("Integration readiness")).toBeVisible();

  await page.getByRole("button", { name: "Use this golden path" }).click();
  await expect(page.getByRole("heading", { name: "Create environment" })).toBeVisible();
  await page.getByLabel("Environment name").fill("smoke-api-dev");
  await page.getByRole("button", { name: "Launch simulated provisioning" }).click();

  await expect(page.getByRole("heading", { name: "Environment status" })).toBeVisible();
  await expect(page.getByText("Provisioning job queued")).toBeVisible();
  await expect(page.getByText("Template validated")).toBeVisible();

  await page.getByRole("button", { name: "Admin", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Platform admin" })).toBeVisible();
  await expect(page.getByText("Access model")).toBeVisible();
  await expect(page.getByRole("tab", { name: "Providers Config and adapters" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Control plane Jobs and approvals" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Governance Queues and controls" })).toBeVisible();
  await expect(page.getByRole("tab", { name: "Templates Catalog and ownership" })).toBeVisible();
  await page.getByRole("tab", { name: "Providers Config and adapters" }).click();
  await expect(page.getByText("Integration configuration")).toBeVisible();
  await expect(page.getByText("Lab adapter pilot")).toBeVisible();
  await expect(page.getByText("Prism read-only inventory")).toBeVisible();
  await expect(page.getByText("Provider readiness")).toBeVisible();
  await page.getByLabel("Endpoint").first().fill("https://prism.lab.example");
  await page.getByLabel("Credential profile").first().fill("nci-readonly");
  await page.getByRole("button", { name: "Save" }).first().click();
  await expect(page.getByText("Configuration saved")).toBeVisible();
  await page.getByRole("button", { name: "Check" }).first().click();
  await expect(page.getByText("Reachable", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Discover" }).first().click();
  await expect(page.getByText("Read-only candidate")).toBeVisible();
  await expect(page.getByText("Provisioning disabled").first()).toBeVisible();
  await page.getByRole("button", { name: "Import inventory" }).click();
  await expect(page.getByText("Rocky Linux 9 Hardened").first()).toBeVisible();
  await expect(page.getByText("Profile candidate").first()).toBeVisible();
  await page.getByRole("tab", { name: "Control plane Jobs and approvals" }).click();
  await expect(page.getByText("Provisioning control plane")).toBeVisible();
  await expect(page.getByRole("heading", { name: "VM sandbox dry-run" })).toBeVisible();
  await page.getByRole("button", { name: "Generate dry-run" }).click();
  await expect(page.getByText("AHV image approved")).toBeVisible();
  await expect(page.getByText("Quota within sandbox limit")).toBeVisible();
  await expect(page.getByText("Rollback plan")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Lab authorization and lifecycle proof" })).toBeVisible();
  await page.getByRole("button", { name: "Record lab scope" }).click();
  await expect(page.getByText("Authorized lab scope / controlled provisioning test window")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Controlled provisioning gate" })).toBeVisible();
  await page.getByRole("button", { name: "Request gate review" }).click();
  await expect(page.getByText("Manual approval required")).toBeVisible();
  await expect(page.getByText("Authorized scope attached")).toBeVisible();
  await expect(page.getByText("Mutation kill switch enabled")).toBeVisible();
  await page.getByRole("button", { name: "Approve gate" }).click();
  await expect(page.getByText("Mutation disabled")).toBeVisible();
  await page.getByRole("button", { name: "Record lifecycle proof" }).click();
  await expect(page.getByText("Controlled gate approved")).toBeVisible();
  await expect(page.getByRole("heading", { name: "Platform service flows" })).toBeVisible();
  await page.getByRole("button", { name: "Plan NDB PostgreSQL" }).click();
  await expect(page.getByText("VM lifecycle proven")).toBeVisible();
  await expect(page.getByText("Complete controlled VM create, verify, rollback, and destroy proof before platform services are enabled.")).toBeVisible();
  await expect(page.getByText("smoke-api-dev").first()).toBeVisible();
  await page.getByRole("button", { name: "Advance" }).first().click();
  await expect(page.getByText("Validating")).toBeVisible();
  await expect(page.getByText("Approval queue")).toBeVisible();
  await expect(page.getByText("ml-reco-lab").first()).toBeVisible();
  await page.getByRole("button", { name: "Approve" }).first().click();
  await expect(page.getByText("Provisioning").first()).toBeVisible();
  await page.getByRole("tab", { name: "Governance Queues and controls" }).click();
  await page.getByRole("button", { name: "Destroy" }).first().click();
  await expect(page.getByText("Destroying").first()).toBeVisible();
  await page.getByRole("tab", { name: "Templates Catalog and ownership" }).click();
  await expect(page.getByText("Image and template catalog")).toBeVisible();
  await expect(page.getByText("Template registry")).toBeVisible();
  await expect(page.getByText("Policy bundles")).toBeVisible();
  await expect(page.getByText("Regulated Data Service").first()).toBeVisible();
  await page.getByRole("button", { name: "Submit review" }).first().click();
  await expect(page.getByText("Pending approval").first()).toBeVisible();
  await page.getByRole("button", { name: "Approve publish" }).first().click();
  await expect(page.getByText("Published").first()).toBeVisible();
  await expect(page.getByText("Template governance")).toBeVisible();
});
