param(
  [ValidateSet("prism-element", "prism-central")]
  [string]$Provider = "prism-element",
  [string]$OutputPath = ".env.lab"
)

$ErrorActionPreference = "Stop"

function Read-RequiredValue {
  param(
    [string]$Prompt,
    [switch]$Secret
  )

  if ($Secret) {
    $secure = Read-Host $Prompt -AsSecureString
    if ($secure.Length -eq 0) {
      throw "$Prompt is required."
    }
    $ptr = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure)
    try {
      return [Runtime.InteropServices.Marshal]::PtrToStringBSTR($ptr)
    } finally {
      [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($ptr)
    }
  }

  $value = Read-Host $Prompt
  if ([string]::IsNullOrWhiteSpace($value)) {
    throw "$Prompt is required."
  }
  return $value.Trim()
}

function Escape-EnvValue {
  param([string]$Value)
  return $Value.Replace("`r", "").Replace("`n", "").Replace('"', '\"')
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$target = if ([IO.Path]::IsPathRooted($OutputPath)) { $OutputPath } else { Join-Path $repoRoot $OutputPath }

if (Test-Path $target) {
  $answer = Read-Host "$target already exists. Overwrite? Type YES to continue"
  if ($answer -ne "YES") {
    throw "Cancelled. Existing lab env file was not changed."
  }
}

$endpointLabel = if ($Provider -eq "prism-element") { "Prism Element URL" } else { "Prism Central URL" }
$endpoint = Read-RequiredValue $endpointLabel
$username = Read-RequiredValue "Prism username"
$password = Read-RequiredValue "Prism password" -Secret
$clusterUuid = Read-RequiredValue "Allowed cluster UUID"
$subnetUuid = Read-RequiredValue "Allowed subnet/network UUID"
$imageUuid = Read-RequiredValue "Allowed image UUID"
$projectUuid = if ($Provider -eq "prism-central") { Read-RequiredValue "Allowed project UUID" } else { "" }
$tlsInsecure = Read-Host "Allow insecure TLS for this lab only? Type true or false"
if ($tlsInsecure -notin @("true", "false")) {
  throw "TLS answer must be true or false."
}

$peAdapterEnabled = if ($Provider -eq "prism-element") { "true" } else { "false" }

$lines = @(
  "# Private AHV lab configuration generated by scripts/new-ahv-lab-env.ps1.",
  "# Do not commit this file.",
  "APP_ENV=lab",
  "HOST=0.0.0.0",
  "PORT=8080",
  "NDC_STUDIO_HOST_PORT=18080",
  "NDC_STATIC_DIR=/app/dist",
  "NDC_DATA_FILE=/data/ndc-studio.json",
  "NDC_REPOSITORY=json",
  "NDC_AUDIT_RETENTION_EVENTS=500",
  "NDC_RATE_LIMIT_PER_MINUTE=120",
  "NDC_REQUIRE_TRUSTED_IDENTITY=false",
  "OIDC_ISSUER_URL=",
  "OIDC_CLIENT_ID=",
  "NDC_AHV_LAB_PROVIDER=$Provider",
  "NDC_AHV_REAL_ADAPTER_ENABLED=true",
  "NDC_AHV_PE_LAB_ADAPTER_ENABLED=$peAdapterEnabled",
  "NDC_CONTROLLED_PROVISIONING_ENABLED=true",
  "NDC_AHV_LAB_LIFECYCLE_ENABLED=false",
  "NDC_PRISM_TLS_INSECURE=$tlsInsecure",
  "NDC_AHV_VM_NAME_PREFIX=ndc-lab-",
  "NDC_AHV_MAX_CPU=4",
  "NDC_AHV_MAX_MEMORY_GB=16",
  "NDC_AHV_MAX_DISK_GB=160",
  "NDC_AHV_DEFAULT_EXPIRY_HOURS=24",
  "NDC_AUTHORIZED_PENTEST_SCOPE_REF=",
  "NDC_AUTHORIZED_PENTEST_SCOPE_ACTIVE=false"
)

if ($Provider -eq "prism-element") {
  $lines += @(
    "NUTANIX_PRISM_ELEMENT_URL=$(Escape-EnvValue $endpoint)",
    "NUTANIX_PRISM_ELEMENT_USERNAME=$(Escape-EnvValue $username)",
    "NUTANIX_PRISM_ELEMENT_PASSWORD=$(Escape-EnvValue $password)",
    "NDC_AHV_PE_ALLOWED_CLUSTER_UUID=$(Escape-EnvValue $clusterUuid)",
    "NDC_AHV_PE_ALLOWED_SUBNET_UUID=$(Escape-EnvValue $subnetUuid)",
    "NDC_AHV_PE_ALLOWED_IMAGE_UUID=$(Escape-EnvValue $imageUuid)",
    "NUTANIX_PRISM_CENTRAL_URL=",
    "NUTANIX_PRISM_USERNAME=",
    "NUTANIX_PRISM_PASSWORD=",
    "NDC_AHV_ALLOWED_CLUSTER_UUID=",
    "NDC_AHV_ALLOWED_PROJECT_UUID=",
    "NDC_AHV_ALLOWED_SUBNET_UUID=",
    "NDC_AHV_ALLOWED_IMAGE_UUID="
  )
} else {
  $lines += @(
    "NUTANIX_PRISM_CENTRAL_URL=$(Escape-EnvValue $endpoint)",
    "NUTANIX_PRISM_USERNAME=$(Escape-EnvValue $username)",
    "NUTANIX_PRISM_PASSWORD=$(Escape-EnvValue $password)",
    "NDC_AHV_ALLOWED_CLUSTER_UUID=$(Escape-EnvValue $clusterUuid)",
    "NDC_AHV_ALLOWED_PROJECT_UUID=$(Escape-EnvValue $projectUuid)",
    "NDC_AHV_ALLOWED_SUBNET_UUID=$(Escape-EnvValue $subnetUuid)",
    "NDC_AHV_ALLOWED_IMAGE_UUID=$(Escape-EnvValue $imageUuid)",
    "NUTANIX_PRISM_ELEMENT_URL=",
    "NUTANIX_PRISM_ELEMENT_USERNAME=",
    "NUTANIX_PRISM_ELEMENT_PASSWORD=",
    "NDC_AHV_PE_ALLOWED_CLUSTER_UUID=",
    "NDC_AHV_PE_ALLOWED_SUBNET_UUID=",
    "NDC_AHV_PE_ALLOWED_IMAGE_UUID="
  )
}

Set-Content -LiteralPath $target -Value $lines -Encoding utf8

Write-Output "Created private AHV lab env file: $target"
Write-Output "Lifecycle mutation remains disabled. Set NDC_AHV_LAB_LIFECYCLE_ENABLED=true only for an authorized create/destroy test."
Write-Output "Next: powershell -NoProfile -ExecutionPolicy Bypass -File ./scripts/test-ahv-lab-readiness.ps1 -EnvFile $OutputPath"
